import Head from 'next/head';
import { useRouter } from 'next/router';

import { chatsList } from '../constants/chats';
import { useDarkMode } from '../hooks/useDarkMode';
import ErrorPage from './404';
import s from './index.module.scss';

export default function Chat() {
  const router = useRouter();
  const { isDark, toggleDark } = useDarkMode();

  const chatPath = (router.query.id || '') as string;

  const currentChat = chatsList.find(chat => chat.path === chatPath);

  if (!currentChat) return <ErrorPage />;

  return (
    <>
      <Head>
        <title>Telegram app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={s.container}>
        <h1 className={s.title}>{currentChat.title}</h1>
        <p className={s.description}>{currentChat.chatContent}</p>
        <button type='button' className={s.button} onClick={toggleDark}>
          switch to {isDark ? 'light mode' : 'dark mode'}
        </button>
      </div>
    </>
  );
}
