import Head from 'next/head';
import { useEffect, useState } from 'react';

import s from './index.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Telegram app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={s.container}>
        <h1 className={s.title}>Hello, World!</h1>
        <p className={s.description}>This next app user tailwind with module scss</p>
      </div>
    </>
  );
}
