name: Deploy dev

on:
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Restart the application
        run: |
          ssh -p 22 zolkinka@92.53.97.252 "pushd /var/www/telegram-landing && git fetch origin && git reset --hard origin/dev && git pull && npm ci --legacy-peer-deps && npm run build && pm2 restart ecosystem.config.js"
